import { expect, test } from '@playwright/test'

async function reset(page: import('@playwright/test').Page) {
  await page.goto('/__proof')
  await expect(page.getByRole('button', { name: 'Executar prova REST' })).toBeVisible()
  await page.evaluate(async () => {
    const response = await fetch('/api/__mock/reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })
    if (!response.ok) throw new Error('Reset failed')
  })
}

async function login(page: import('@playwright/test').Page, email = 'collector-a@example.test') {
  await page.goto('/login')
  await page.getByLabel(/^E-mail/).fill(email)
  await page.getByLabel(/^Senha/).fill('DemoNft!2026')
  await page.getByRole('main').getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect.poll(() => new URL(page.url()).pathname).toBe('/')
}

test.beforeEach(async ({ page }) => reset(page))

test('protected routes return to their destination after sign-in and session survives refresh', async ({ page }) => {
  await page.goto('/profile')
  await expect(page).toHaveURL(/\/login\?returnTo=%2Fprofile$/)
  await page.getByLabel(/^E-mail/).fill('collector-a@example.test')
  await page.getByLabel(/^Senha/).fill('DemoNft!2026')
  await page.getByRole('main').getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page).toHaveURL(/\/profile$/)
  await expect(page.getByRole('heading', { name: 'Perfil do colecionador' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Sair' })).toBeVisible()
})

test('desktop opens the login dialog over the current page; mobile keeps the login route', async ({ page, isMobile }) => {
  if (isMobile) {
    await page.goto('/nfts/nft-001')
    await page.getByRole('link', { name: 'Entrar para favoritar Violet Nomad' }).click()
    await expect(page).toHaveURL(/\/login\?returnTo=%2Fnfts%2Fnft-001$/)
    await expect(page.getByRole('heading', { name: 'Entrar na Kurio' })).toBeVisible()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    return
  }

  await page.goto('/')
  const enter = page.getByRole('banner').getByRole('link', { name: 'Entrar', exact: true })
  await enter.click()
  const dialog = page.getByRole('dialog', { name: 'Entrar na Kurio' })
  await expect(dialog).toBeVisible()
  const dialogCenter = await dialog.evaluate(element => {
    const { x, y, width, height } = element.getBoundingClientRect()
    return { width, height, x: x + width / 2, y: y + height / 2, viewportX: innerWidth / 2, viewportY: innerHeight / 2 }
  })
  expect(dialogCenter.width).toBe(500)
  expect(dialogCenter.height).toBe(600)
  expect(dialogCenter.x).toBeCloseTo(dialogCenter.viewportX, 0)
  expect(dialogCenter.y).toBeCloseTo(dialogCenter.viewportY, 0)
  await expect(page.getByRole('heading', { name: 'Seja dono do futuro da arte digital' })).toBeVisible()
  await expect(page).toHaveURL(/\/$|\/?\?.*/)
  await dialog.click({ position: { x: 5, y: dialogCenter.height - 20 } })
  await expect(dialog).toBeVisible()
  await page.mouse.click(5, 5)
  await expect(dialog).not.toBeVisible()
  await expect(enter).toBeFocused()

  await enter.click()
  const escapeDialog = page.getByRole('dialog', { name: 'Entrar na Kurio' })
  await page.keyboard.press('Escape')
  await expect(escapeDialog).not.toBeVisible()
  await expect(enter).toBeFocused()

  await enter.click()
  const loginDialog = page.getByRole('dialog')
  const authTabs = loginDialog.getByRole('navigation', { name: 'Autenticação' })
  const closeButton = loginDialog.getByRole('button', { name: 'Fechar janela de autenticação' })
  const closeBox = await closeButton.boundingBox()
  const tabsBox = await authTabs.boundingBox()
  expect(closeBox).not.toBeNull()
  expect(tabsBox).not.toBeNull()
  expect(tabsBox!.y).toBeGreaterThan(closeBox!.y + closeBox!.height)
  await authTabs.getByRole('button', { name: 'Criar conta' }).click()
  const displayName = loginDialog.getByLabel(/^Nome de exibição/)
  await expect(displayName).toBeVisible()
  await expect(displayName).toBeFocused()
  await authTabs.getByRole('button', { name: 'Entrar', exact: true }).click()
  const emailInput = loginDialog.getByLabel(/^E-mail/)
  const passwordInput = loginDialog.getByLabel(/^Senha/)
  await expect(passwordInput).not.toBeFocused()
  await expect(emailInput).toBeFocused()
  await expect(emailInput).toHaveCSS('border-top-color', 'rgb(210, 138, 76)')
  await expect(passwordInput).toHaveCSS('border-top-color', 'rgb(75, 43, 31)')
  await loginDialog.getByRole('button', { name: 'Mostrar senha' }).click()
  await expect(passwordInput).toHaveAttribute('type', 'text')
  await loginDialog.getByRole('button', { name: 'Ocultar senha' }).click()
  await loginDialog.getByRole('button', { name: 'Esqueceu a senha?' }).click()
  await expect(loginDialog.getByRole('status')).toHaveText('A recuperação de senha não está disponível nesta demonstração.')
  await loginDialog.getByRole('button', { name: 'Continuar com Google' }).click()
  await expect(loginDialog.getByRole('status')).toHaveText('O login com Google não está disponível nesta demonstração.')
  await loginDialog.getByLabel(/^E-mail/).fill('collector-a@example.test')
  await loginDialog.getByLabel(/^Senha/).fill('DemoNft!2026')
  await loginDialog.locator('form').getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(loginDialog).not.toBeVisible()
  await expect(page.getByRole('banner').getByRole('button', { name: 'Sair' })).toBeVisible()
})

test('registration creates a session and rejects duplicate accounts', async ({ page }) => {
  await page.goto('/register?returnTo=%2Fprofile')
  await page.getByLabel(/^Nome de exibição/).fill('Nova Pessoa')
  await page.getByLabel(/^Nome de usuário/).fill('nova-pessoa')
  await page.getByLabel(/^E-mail/).fill('nova@example.test')
  await page.getByLabel(/^Senha/).fill('SenhaNova2026')
  await page.getByRole('button', { name: 'Criar conta' }).click()
  await expect(page).toHaveURL(/\/profile$/)
  await expect(page.getByRole('button', { name: 'Sair' })).toBeVisible()
  await page.getByRole('button', { name: 'Sair' }).click()
  await page.goto('/register?returnTo=%2Fprofile')
  await page.getByLabel(/^Nome de exibição/).fill('Outra Pessoa')
  await page.getByLabel(/^Nome de usuário/).fill('outra-pessoa')
  await page.getByLabel(/^E-mail/).fill('nova@example.test')
  await page.getByLabel(/^Senha/).fill('SenhaNova2026')
  await page.getByRole('button', { name: 'Criar conta' }).click()
  await expect(page.getByRole('alert')).toContainText('Já existe uma conta')
})

test('favorites update optimistically, roll back on failure and remain isolated by user', async ({ page }) => {
  await login(page)
  await expect(page).toHaveURL(/\/$/)
  await page.goto('/nfts/nft-001')
  const remove = page.getByRole('button', { name: 'Remover Violet Nomad dos favoritos' }).first()
  await expect(remove).toHaveAttribute('aria-pressed', 'true')
  await remove.click()
  const add = page.getByRole('button', { name: 'Favoritar Violet Nomad' }).first()
  await expect(add).toHaveAttribute('aria-pressed', 'false')
  await page.evaluate(async () => {
    const response = await fetch('/api/__mock/favorite-network', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ failuresRemaining: 1, delayMs: 400 }) })
    if (!response.ok) throw new Error('Network control failed')
  })
  const failedUpdate = page.waitForResponse(response => response.url().endsWith('/api/me/favorites/nft-001') && response.status() === 503)
  await add.click()
  await expect(page.getByRole('button', { name: 'Remover Violet Nomad dos favoritos' }).first()).toHaveAttribute('aria-pressed', 'true')
  await failedUpdate
  await expect(page.getByRole('button', { name: 'Favoritar Violet Nomad' }).first()).toHaveAttribute('aria-pressed', 'false')
  await page.goto('/profile')
  await page.getByRole('button', { name: 'Sair' }).click()
  await expect.poll(() => new URL(page.url()).pathname).toBe('/')
  await login(page, 'collector-b@example.test')
  await page.goto('/profile')
  await expect(page.getByRole('heading', { name: 'Perfil do colecionador' })).toBeVisible()
  await page.goto('/nfts/nft-001')
  await expect(page.getByRole('button', { name: 'Favoritar Violet Nomad' }).first()).toHaveAttribute('aria-pressed', 'false')
})
