import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/__proof')
  await expect(page.getByRole('button', { name: 'Executar prova REST' })).toBeVisible()
  await page.evaluate(async () => {
    const response = await fetch('/api/__mock/reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' })
    if (!response.ok) throw new Error('Reset failed')
  })
})

test('visitor cart persists, updates quantity and calculates valid coupon totals', async ({ page, isMobile }) => {
  await page.goto('/nfts/nft-001')
  await expect(page.getByRole('heading', { name: 'Violet Nomad', exact: true })).toBeVisible()
  const add = page.getByRole('button', { name: /Adicionar.*carrinho/i })
  await add.click()
  await expect(page.getByRole('status').filter({ hasText: 'Adicionado ao carrinho.' })).toBeVisible()
  await page.goto('/cart')
  await expect(page.getByRole('navigation', { name: 'Caminho da página' })).toContainText('Início / Mercado / Carrinho')
  if (!isMobile) await expect(page.getByRole('banner').getByRole('link', { name: 'Mercado', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('heading', { name: 'Resumo da carteira' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Colecionadores também viram' })).toBeVisible()
  const cartItem = page.getByRole('link', { name: 'Ver Violet Nomad', exact: true })
  await expect(cartItem).toBeVisible()
  await page.reload()
  await expect(cartItem).toBeVisible()
  await page.getByRole('button', { name: 'Aumentar Violet Nomad' }).click()
  await expect(page.getByLabel('Quantidade de Violet Nomad selecionada')).toHaveText('2')
  await page.getByLabel('Código promocional', { exact: true }).fill('NFT10')
  await page.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await expect(page.getByText('Cupom NFT10')).toBeVisible()
  await expect(page.getByRole('complementary').getByText('0.019 ETH', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Remover Violet Nomad' }).click()
  await expect(page.getByRole('heading', { name: 'Seu carrinho está vazio' })).toBeVisible()
})

test('login merges visitor items once and keeps them in the account cart', async ({ page }) => {
  await page.goto('/nfts/nft-001')
  await page.getByRole('button', { name: /Adicionar.*carrinho/i }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Adicionado ao carrinho.' })).toBeVisible()
  await page.goto('/login')
  await page.getByLabel('E-mail', { exact: true }).fill('collector-a@example.test')
  await page.getByLabel('Senha', { exact: true }).fill('DemoNft!2026')
  const mergeResponsePromise = page.waitForResponse(response => response.url().endsWith('/api/cart/merge'))
  await page.getByRole('main').getByRole('button', { name: 'Entrar', exact: true }).click()
  const mergeResponse = await mergeResponsePromise
  expect(mergeResponse.ok()).toBeTruthy()
  expect((await mergeResponse.json()).items).toHaveLength(1)
  await page.goto('/cart')
  await expect(page.getByRole('link', { name: 'Ver Violet Nomad', exact: true })).toBeVisible()
  await expect(page.getByLabel('Quantidade de Violet Nomad selecionada')).toHaveText('1')
})

test('invalid coupons show an API error without changing cart totals', async ({ page }) => {
  await page.goto('/nfts/nft-001')
  await page.getByRole('button', { name: /Adicionar.*carrinho/i }).click()
  await page.goto('/cart')
  const total = page.getByRole('complementary').getByText('0.011 ETH', { exact: true })
  await expect(total).toBeVisible()
  await page.getByLabel('Código promocional', { exact: true }).fill('INVALID')
  await page.getByRole('button', { name: 'Aplicar', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Cupom inválido.')
  await expect(total).toBeVisible()
})
